# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-16 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20190816_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者表'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '书籍', 'verbose_name_plural': '书籍表'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
